name: Deploy


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          # depends on the server we will use to deploy
          # heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # heroku_app_name: "<YOUR_HEROKU_APP_NAME>"
          # heroku_email: "<YOUR_HEROKU_EMAIL>"
          usedocker: true